GET http://localhost:3003/users/
Content-Type: application/json
### 
GET http://localhost:3003/users/user/id=639300e1a74d1deccc0bfb90
Content-Type: application/json
### 
GET http://localhost:3003/users/user/username=xxx
Content-Type: application/json

### 
POST http://localhost:3001/users
content-type: application/json

{
    "username": "Jonne",
    "password": "123",
    "avatar": "xtxxx"
}

###
PUT http://localhost:3003/posts/639c47c53bfd905c671c282e HTTP/1.1
content-type: application/json

{
    "text": "tää on muokattu teksti"
}